require("plugins")
require("keymaps")
require("editor")

require("bc-formatter")
require("bc-galaxyline")
require("bc-gitsigns")
require("bc-comment")
require("bc-nvimtree")
require("bc-telescope")
require("bc-treesitter")
require("bc-compe")
require("bc-pairs")
require("bc-colorizer")
require("bc-vimwiki")

require("lsp-config")
require("languages")

vim.cmd("colorscheme subtle_dark")
