require("plugins")
require("keymaps")
require("bc-editor")

require("bc-formatter")
require("bc-bufferline")
require("bc-lualine")
require("bc-gitsigns")
require("bc-comment")
require("bc-nvimtree")
require("bc-telescope")
require("bc-treesitter")
require("bc-compe")
require("bc-pairs")
require("bc-colorizer")
require("bc-wiki")
require("bc-rest")

require("bc-lsp")
require("languages")

require("bc-colorscheme")
