#!/bin/sh
# alias para programas
alias ls='lsd' \
      cat='bat' \
      reds='redshift -P -O 3500 -b .7' \
      upd='sudo pacman -Syu' \
      res='du -h --max-depth=1' \
	  shutdown='shutdown -h now'

# alias
alias tmux='before_tmux.sh' \
      jap='exec fcitx5 &'

# alias para ubicaciones
alias conf='cd ~/Documents/configs/' \
      proy='cd ~/proyectos/' \
      pgo='cd ~/proyectos/go/' \
      pgoa='cd ~/proyectos/go/aula_virtual/' \
      ppy='cd ~/proyectos/python/' \
      pru='cd ~/proyectos/rust/' \
      pjs='cd ~/proyectos/node/'


# alias open configs
alias neoconf='nvim ~/Documents/configs/nvim/init.vim' \
	  nconf='cd ~/Documents/configs/nvim/lua-configs/ && nvim init.lua' \
      bashconf='nvim ~/Documents/configs/bash-configs/bashrc' \
      profileconf='nvim ~/Documents/configs/bash-configs/bash_profile' \
      aliasconf='nvim ~/Documents/configs/bash-configs/aliasrc' \
      alaconf='nvim ~/Documents/configs/alacritty/alacritty.yml'
